### ISSUE TITLE
Fatal error InternalItemsController

### ISSUE THREAD

**Issue by richardkorthuis** [OpenWebconcept/plugin-pdc-internal-products#3]
**Beschrijf de bug**
De InternalItemsController geeft een PHP Fatal error op de REST API:
`PHP Fatal error:  Type of OWC\PDC\InternalProducts\RestAPI\InternalItemsController::$plugin must not be defined (as in class OWC\PDC\Base\RestAPI\Controllers\BaseController) in [...]\public_html\wp-content\plugins\pdc-internal-products\src\InternalProducts\RestAPI\InternalItemsController.php on line 146`

**Te reproduceren**
Stappen om het gedrag te reproduceren:
1. Installeer en activeer de laatste versie van de plugin PDC Base (versie 3.6.4) op een schone WordPress installatie
2. Installeer en activeer de laatste versie van de plugin PDC Internal Products (versie 3.0.3)
3. Doe een call naar de REST API (https://[site-url]/wp-json) > Fatal error

**Verwacht gedrag**
Geen Fatal error

**Schermafbeeldingen**
nvt

**Desktop (vul de volgende informatie in):**
nvt

**Smartphone (vul de volgende gegevens in):**
nvt

**Comment by mvdhoek1** [comment]
Weet je zeker dat je op deze versies zit? Bij mij lokaal en op productie gaat het goed op deze versies.

**Comment by richardkorthuis** [comment]
@mvdhoek1 Ik weet zeker dat ik op het moment van de fatal error op deze versies zat. Ik heb het namelijk nog speciaal een keer getest op een compleet schone WP installatie om er zeker van te zijn dat het probleem niet ergens in mijn configuratie zat. Het vreemde is echter dat ik het zojuist nogmaals heb getest en de error nu niet meer optreedt. Het enige wat ik in de tussentijd wel een keer heb gedaan is mijn composer cache geleegd. Ik vermoed dus dat er in mijn cache iets verkeerd heeft gestaan waardoor deze fout optrad.

Voor nu kan dit issue dus dicht, mocht het zich toch weer voordoen dan hoor je van mij.

**Comment by mvdhoek1** [comment]
Helemaal goed, deze fatal error zat er wel in maar 1 versie lager. Deze had ik al opgelost toen.
